[profile.default]
src = "."
out = "out"
libs = [
    "../../../packages/erc4337-contracts/dependencies",
    "../../../node_modules/.pnpm/@matterlabs+zksync-contracts@0.6.1_@openzeppelin+contracts-upgradeable@4.9.6_@openzeppelin+contracts@5.4.0/node_modules"
]
solc_version = "0.8.30"

# Remappings to access dependencies from erc4337-contracts
remappings = [
    "forge-std/=../../../packages/erc4337-contracts/dependencies/forge-std/src/",
    "account-abstraction/=../../../packages/erc4337-contracts/dependencies/account-abstraction/contracts/",
    "@openzeppelin/contracts/=../../../packages/erc4337-contracts/dependencies/openzeppelin-contracts/contracts/",
]

